// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuOz-Fu0Y93NLLtJC9liJ5PYoWM7eFYr0',
    appId: '1:220196360194:web:97988bb83fd7be1025971b',
    messagingSenderId: '220196360194',
    projectId: 'chatapp-64fcb',
    authDomain: 'chatapp-64fcb.firebaseapp.com',
    storageBucket: 'chatapp-64fcb.firebasestorage.app',
    measurementId: 'G-QXJJ8MYHR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlKwCSnZX6q0okZmkVMhgxlK5hkpFAhiI',
    appId: '1:220196360194:android:f6d39d1384fa2bfe25971b',
    messagingSenderId: '220196360194',
    projectId: 'chatapp-64fcb',
    storageBucket: 'chatapp-64fcb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQT8aNK5nBEL_Fvpb0nk3PSoWwKxWgX5Q',
    appId: '1:220196360194:ios:498ac00f7d89ab8025971b',
    messagingSenderId: '220196360194',
    projectId: 'chatapp-64fcb',
    storageBucket: 'chatapp-64fcb.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQT8aNK5nBEL_Fvpb0nk3PSoWwKxWgX5Q',
    appId: '1:220196360194:ios:498ac00f7d89ab8025971b',
    messagingSenderId: '220196360194',
    projectId: 'chatapp-64fcb',
    storageBucket: 'chatapp-64fcb.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuOz-Fu0Y93NLLtJC9liJ5PYoWM7eFYr0',
    appId: '1:220196360194:web:ee90626ea6dd0c1d25971b',
    messagingSenderId: '220196360194',
    projectId: 'chatapp-64fcb',
    authDomain: 'chatapp-64fcb.firebaseapp.com',
    storageBucket: 'chatapp-64fcb.firebasestorage.app',
    measurementId: 'G-RDSZ089F6H',
  );
}
